name: Releases
on:
  push:
    branches:
      - main
    paths-ignore:
      - "data/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "main-branch"

jobs:
  release:
    if: github.repository == 'zarcode/conventional-release'
    runs-on: ubuntu-latest

    steps:
      # check out the repository
      - uses: actions/checkout@v3

      # run the release-please action
      - uses: google-github-actions/release-please-action@v3
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
