name: Conventional Changelog Action
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Softprops Action Gh Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CHANGELOG.md
          token: ${{ secrets.CHANGELOG_RELEASE }}
