name: Releases
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "data/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "main-branch"

jobs:
  release:
    if: github.repository == 'zarcode/conventional-release'
    runs-on: ubuntu-latest

    steps:
      # check out the repository
      - uses: actions/checkout@v2

      # run the release-please action
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.CHANGELOG_RELEASE }}
          release-type: node
          package-name: release-please-action

      # create release with last commit
      - name: create release with last commit
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
          tag_name: ${{ steps.release.outputs.tag }}
          release_name: ${{ steps.release.outputs.tag }}
          body: ${{ steps.release.outputs.changelog }}
