name: Releases
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "data/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "main-branch"

jobs:
  release:
    if: github.repository == 'zarcode/conventional-release'
    runs-on: ubuntu-latest

    steps:
      # check out the repository
      - uses: actions/checkout@v3

      # run the release-please action
      - uses: google-github-actions/release-please-action@v3
        id: changelog
        with:
          token: ${{ secrets.CHANGELOG_RELEASE }}
          release-type: node
          package-name: release-please-action

      - name: Print changelog outputs
        run: echo "${{ toJson(steps.changelog.outputs) }}"

      # create release with last commit
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.CHANGELOG_RELEASE }}
          tag: ${{ steps.changelog.outputs.tag_name }}
          bodyFile: "CHANGELOG.md"
